version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Kolkata
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: ini
    versions:
    - 1.3.8
